Fullscreen shell example
Z572/guile-wlroots pull request #4
Opened 2023-06-11 00:12 UTC by WammKD

I think this example only takes fullscreen so I can't run it inside of an already-running Wayland instance (at least, I don't think) so I can't test it, in full, but I think, even if there's anything which still needs finishing, I think there's much more which is properly finished than not. The places where I'm uncertain, I'll leave comments.

I put comments throughout the example to the line number from the original C file so it's easier for new users to compare what happened in the original with the `guile-wlroots` version.

2023-06-11 09:45 UTC, Z572 requested changes

2023-06-11 09:45 UTC, Z572 commented on wlroots/types/fullscreen-shell-v1.scm
> +(define-module (wlroots types fullscreen-shell-v1)
please remove v1, different version should in same module，user should known what version need, so just import `(wlroots types fullscreen-shell)` and use expect version procedure

2023-06-11 09:45 UTC, Z572 commented on wlroots/types/fullscreen-shell-v1.scm
> +            wlr-fullscreen-shell-v1-present-surface-event
should `<wlr-fullscreen-shell-v1-present-surface-event> `, define-wlr-types-class auto add `<` `>`

2023-06-11 09:45 UTC, Z572 commented on wlroots/types/output.scm
> +    (values (bytestructure-ref width) (bytestructure-ref height))))
i think should use `cons`, just get a width is not usually

2023-06-11 09:45 UTC, Z572 commented on wlroots/render/renderer.scm
> +                 (if (>= (length matrix) 9)
i don't think > 9 is usually,maybe just 9.

2023-06-11 09:45 UTC, Z572 commented on wlroots/render/renderer.scm
> +                   (error "warning: list argument is too small; matrix requires, at least, 9"))
don't use `warning: ` begin, and use `srfi-34` `raise` like
`(raise (condition
                (&message
                 (message  "Not a 9 length vector or list"))))`

2023-06-11 09:45 UTC, Z572 commented on wlroots/render/renderer.scm
> +                                      (list->vector matrix)))
please allow pass vector

2023-06-11 09:45 UTC, Z572 commented on wlroots/render/renderer.scm
> +                   (error "warning: list argument is too small; projection requires, at least, 9"))
same

2023-06-11 09:45 UTC, Z572 commented on wlroots/render/renderer.scm
> +                 (if (>= (length projection) 9)
same

2023-06-11 09:45 UTC, Z572 commented on wlroots/types/matrix.scm
> +       (if (>= (length projection) max-vector-length)
can add a procedure to do convert from 9 length vector or list to bytestructure, and use it.

2023-06-11 09:45 UTC, Z572 commented on wlroots/types/matrix.scm
> +                                                  (list->vector projection)))
same

2023-06-11 09:45 UTC, Z572 commented on wlroots/types/transform.scm
> +(define-module (wlroots types transform)
no need this module, please move procedures to `(wlroots types output)`

2023-06-11 09:45 UTC, Z572 commented on wlroots/types/transform.scm
> +  ('* "wlr_output_transform_invert" '(*))
use `ffi:int32` like `(ffi:int32 "wlr_output_transform_invert" (list ffi:int32))`

2023-06-11 09:45 UTC, Z572 commented on wlroots/types/transform.scm
> +  ('* "wlr_output_transform_compose" '(* *))
same

2023-06-11 09:45 UTC, Z572 commented on wlroots/types/transform.scm
> +(define-wlr-procedure (wlr-output-transform-compose tr_a tr_b)
tr-a tr-b

2023-06-11 09:45 UTC, Z572 commented on wlroots.scm
> +             (types fullscreen-shell-v1)
move this to add scm file's same commit

2023-06-11 09:45 UTC, Z572 commented on example/fullscreen-shell.scm
> +             (ice-9          format)
`((ice-9 format) #:select (format))` is better than comment.

2023-06-11 09:45 UTC, Z572 commented on example/fullscreen-shell.scm
> +(use-modules (ice-9          curried-definitions)
just one space

2023-06-11 09:45 UTC, Z572 commented on example/fullscreen-shell.scm
> +  (let ([listener (make-wl-listener proc)])
please don't use `[]`, `()` is good.

2023-06-11 09:45 UTC, Z572 commented on example/fullscreen-shell.scm
> +  (let-values ([(renderer)     (get-server-renderer (get-output-server fullscreen-output))]
use `(srfi srfi-71)`'s `let`

2023-06-11 09:45 UTC, Z572 commented on wlroots/types/drm.scm
> +;; properly. In particular, flink handles are left unimplemented.
please remove this comment, guile-wlroots is a ffi library

2023-06-11 09:49 UTC, Z572 commented
you can try it at tty use tmux and ssh.
run `example/fullscreen-shell.scm` at tmux, and open a ssh to connect you computer, use `tmux a` to attach tmux, and look log or send <kbd>C-c</kbd>

2023-06-11 09:51 UTC, Z572 commented
i get a black screen after run it, is normal?

2023-06-11 20:30 UTC, WammKD commented
Hmm; I'm not sure I'm doing the `tmux` thing properly. I started `tmux` in one of the TTYs and then went back to my main TTY and ran a `tmux a`, like you suggested. It connected but running `example/fullscreen-shell.scm` caused it to switch from TTY 1 to the other TTY and I was stuck as before, with the screen unable to process input so not able to do anything.

As to getting a black screen, I believe so? The only comment they've provided new users is "A minimal fullscreen-shell server. It only supports rendering." so I think it's very similar to the `scene-graph` example, just not using the new Scene Graph API.

2023-06-12 05:11 UTC, Z572 commented
i rebase and pushed at 490e276aa1943447a069c6c4e042614dfb259903, but not push example/fullscreen.scm, need check why black screen, 
wait https://github.com/Z572/guile-wlroots/tree/fullscreen-shell-example-fixed.

2023-06-12 05:11 UTC, closed without merging

2023-06-25 16:37 UTC, Z572 commented
now add at f47d4bd6bdac5e60e6a278e996d9c84d72f6f610, because `wlr-renderer-end` is in `(when (get-output-surface fullscreen-output) something)`, when move out, success.